### ISSUE TITLE
Documentation: Timeline Plugin

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka/plugin-Timeline#3]
Testing Issue #1 for reference--let me know if I can assist or explain something, thanks!

**Comment by katknow** [comment]
[Here's a draft I'm still working on](https://github.com/katknow/Drafts/blob/6627b949b0837fc9782e5b1cac564a15bf54b5ca/timeline.md), but quick question before I continue--does the section on timeline compatibility with exhibit builder go in this documentation or in the exhibit builder documentation (I'm thinking back to this issue: [https://github.com/omeka-s-modules/Mapping/issues/92](https://github.com/omeka-s-modules/Mapping/issues/92)? Or maybe does it go in both?

**Comment by sharonmleon** [comment]
This is likely a good question for @allanaaa

**Comment by allanaaa** [comment]
I would just say "Timeline integrates with the [Exhibit Builder plugin](), by adding a new Timeline block option to exhibit pages." on the Timeline page. I'd add subsections for it and Geolocation (and Exhibit Image Annotation too I guess) on the Exhibit Builder page in the "Additional layouts" section (and then use that heading link). There isn't anything you can really do in the Exhibits interface, in terms of settings, so it doesn't need much detail on either page, maybe just a screengrab of the New Block frame on the Timeline page.

Geolocation has the same problem, and I'd say it's a bit too repetitive on both pages:
https://omeka.org/classic/docs/Plugins/Geolocation/#geolocation-and-exhibit-builder

You'll also need to add a Timeline section to the Plugin Shortcodes page, same deal:
https://omeka.org/classic/docs/Content/Shortcodes/#plugin-shortcodes

**Comment by katknow** [comment]
I created a new branch in the enduser repo that includes the [Timeline documentation draft](https://github.com/omeka/classic-enduser/blob/b416166369f5dc3c791bb10c55b25edecacb89fa/docs/Plugins/Timeline.md). I've also made edits to the [Exhibit Builder](https://github.com/omeka/classic-enduser/blob/timeline/docs/Plugins/ExhibitBuilder.md) page and the [Shortcodes](https://github.com/omeka/classic-enduser/blob/bcd355e23ce86b5cf4c7316dea4b18556a48c388/docs/Content/Shortcodes.md) page. @allanaaa once we decide its good I can pare down the Geolocation page to match it if you want and its section on Exhibit Builder (I can also add info on Annotation)

One thing that we might want changed is that I just noticed in exhibit builder when you go to add a new timeline block it says timeline twice:

![image](https://user-images.githubusercontent.com/84726696/211239319-181ee246-2798-4157-97d7-8cada8316870.png)

**Comment by allanaaa** [comment]
That "Timeline timeline" is fixed now. If you're happy with your documentation, go ahead and make a pull request and I'll do one last review of your changes. I just did some last testing in themes but I think we're good to go on this.

**Comment by katknow** [comment]
@allanaaa just to clarify, am I making a pull request to merge it with the main branch?

**Comment by matthewjmckinley** [comment]
@allanaaa @katknow I think this plugin is ready to go now from a testing perspective--is the documentation ready also?

**Comment by katknow** [comment]
@matthewjmckinley I think it is! There is a timeline branch on the documentation repo
