### ISSUE TITLE
Timeline breaks with Search by Metadata

### ISSUE THREAD

**Issue by allanaaa** [omeka/plugin-Timeline#5]
When the Search By Metadata plugin is active, and when "date" is checked, the Timelines won't load any items. 

![timeline](https://user-images.githubusercontent.com/28012148/213011436-14d720ae-798c-41eb-8a81-ce56f2a24cc1.PNG)

It worked fine when I checked "title" - titles in the timeline part became links. Same with descriptions. So it's only having a funny interaction with date-based fields. Including coverage - if the timeline is otherwise working, but coverage is checked in SBM, you won't get durations to display, either above the title in the card or in the timeline below:

![coverage](https://user-images.githubusercontent.com/28012148/213015876-780e2031-7412-4bb1-8b3e-55d0a54601da.PNG)
![coverage2](https://user-images.githubusercontent.com/28012148/213015879-f66dac55-a930-449b-9718-727c0e7d1145.PNG)

**Comment by zerocrates** [comment]
@matthewjmckinley there's a `no_filter` option for `metadata()` that should fix this issue

**Comment by matthewjmckinley** [comment]
Fixed in https://github.com/omeka/plugin-Timeline/commit/f4e1e9cc3601e2484619148b1a02cb52114a2233
