### ISSUE TITLE
Timeline and Search by Metadata interaction, + misc

### ISSUE THREAD

**Issue by allanaaa** [omeka/plugin-Timeline#7]
Probably just an untested extension of #5, when Search by Metadata is enabled and a Timeline is using a searchable field, SBM overrides the links. I'm using a "Region" field as my title in the timeline, and when I click on the region, it takes me to the SBM results rather than to the item page. 

It's also adding a SBM link into the mini-flag in the timeline itself, which I don't think too many people will want. Can we just get SBM to ignore anything happening inside the timeline area?

Finally, we should cut off long descriptions just short of the height of the timeline bar - I think better put in the timeline CSS than into themes. The timeline is getting a height of 500px, and the images are max-height:305px, so the text box including the title should get the same. If we can do something extra fancy like cut off the text with an ellipsis, I think that's done by code and not CSS. 

![timeline-issues](https://github.com/omeka/plugin-Timeline/assets/28012148/2a5aebf1-30ba-42cd-a0da-b2c68656e455)

**Comment by matthewjmckinley** [comment]
SBM issues fixed in b58b11feb0aa849994504ab1ec27bd74a0570e48 , continuing to investigate truncating description field
