### ISSUE TITLE
Timeline breaks without an Interval selection

### ISSUE THREAD

**Issue by allanaaa** [omeka/plugin-Timeline#9]
Even if the user has no interval data and doesn't plan to use it, you can't create or save a timeline without something selected in the "Item interval field" dropdown. 
Can we make this field optional? Alternatively, we should put something in the interface to warn users to select something, anything, if they want to proceed.

**Comment by matthewjmckinley** [comment]
Fixed in 4ad770ada9172eecbcb06a4e602105c2d59d419b
